// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKC6IY-kRfBo4r6rQrLeNw5GEUKJKyjTc',
    appId: '1:318540822477:web:0309d500926e56450cf684',
    messagingSenderId: '318540822477',
    projectId: 'healthcare-plus-d52c0',
    authDomain: 'healthcare-plus-d52c0.firebaseapp.com',
    databaseURL: 'https://healthcare-plus-d52c0-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-plus-d52c0.firebasestorage.app',
    measurementId: 'G-JDPZ1YTHWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG3hskUp7sBSedGU8yfgB9Vx14onmkFJI',
    appId: '1:318540822477:android:c5cd8af6c2c66f240cf684',
    messagingSenderId: '318540822477',
    projectId: 'healthcare-plus-d52c0',
    databaseURL: 'https://healthcare-plus-d52c0-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-plus-d52c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBlElnwVfq54MWEh0ASWlFv_AVD04lE7g',
    appId: '1:318540822477:ios:55b631ff61a4887b0cf684',
    messagingSenderId: '318540822477',
    projectId: 'healthcare-plus-d52c0',
    databaseURL: 'https://healthcare-plus-d52c0-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-plus-d52c0.firebasestorage.app',
    iosBundleId: 'com.aryahsworld.healthcarePlus',
  );
}
